#!/bin/bash
# Prevents force-pushing to master
# Taken from https://gist.github.com/pixelhandler/5718585

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|develop|rc)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  echo "Never push directly to \"$BRANCH\" (Prevented push to protected branch by pre-push hook)"
  echo "If you really want to do this, use --no-verify to bypass this pre-push hook."
  exit 1
fi

exit 0